Update argocd.yml

diff --git a/.github/workflows/argocd.yml b/.github/workflows/argocd.yml
--- a/.github/workflows/argocd.yml
+++ b/.github/workflows/argocd.yml
@@ -2,7 +2,7 @@ name: ArgoCD Auto-Update Deployment on Image Change
 
 on:
   schedule:
-    - cron: '*/5 * * * *'  # Every 5 minutes.
+    - cron: '*/5 * * * *'  # Every 5 minutes
 
 jobs:
   update-deployment:
@@ -11,30 +11,33 @@ jobs:
       - name: Checkout the repository
         uses: actions/checkout@v2
       
-      - name: List files in the deployments directory
+      - name: Display the content of deployment.yml
         run: |
-          echo "Listing contents of the deployments directory:"
-          ls -alh deployments/
+          echo "Displaying the contents of deployment.yml:"
+          cat deployments/deployment.yml
+
+      - name: Get latest image tag from Docker Hub
+        id: dockertag
+        run: |
+          TAG=$(curl -s "https://hub.docker.com/v2/repositories/ezio22/argocd-node-app/tags" | jq -r '.results[0].name')
+          if [[ -z "$TAG" || "$TAG" == "null" ]]; then
+            echo "Failed to fetch tag, or tag is null."
+            exit 1
+          fi
+          echo "Latest tag fetched: $TAG"
+          echo "::set-output name=tag::$TAG"
       
-      - name: Get latest image digest from Docker Hub
-        id: dockerhub
+      - name: Extract current tag and update if necessary
         run: |
-          DIGEST=$(curl -s "https://hub.docker.com/v2/repositories/ezio22/argocd-node-app/tags/latest" | jq -r '.images[] | select(.architecture=="amd64").digest')
-          echo "Latest digest fetched: $DIGEST"
-          echo "::set-output name=digest::$DIGEST"
-      
-      - name: Update the Deployment file if new image is available
-        if: steps.dockerhub.outputs.digest != ''
-        run: |
-          CURRENT_DIGEST=$(grep -o 'ezio22/argocd-node-app@[a-z0-9]*' deployments/deployment.yml | cut -d '@' -f 2)
-          echo "Current digest in deployment.yml: $CURRENT_DIGEST"
-          if [ "$CURRENT_DIGEST" != "${{ steps.dockerhub.outputs.digest }}" ]; then
-            echo "Updating deployment.yml with new digest..."
-            sed -i "s|ezio22/argocd-node-app@${CURRENT_DIGEST}|ezio22/argocd-node-app@${{ steps.dockerhub.outputs.digest }}|" deployments/deployment.yml
+          CURRENT_TAG=$(grep -o 'ezio22/argocd-node-app:[^ ]*' deployments/deployment.yml | cut -d ':' -f 2)
+          echo "Current tag in deployment.yml: $CURRENT_TAG"
+          if [ "$CURRENT_TAG" != "${{ steps.dockertag.outputs.tag }}" ]; then
+            echo "Updating deployment.yml with new tag..."
+            sed -i "s|ezio22/argocd-node-app:$CURRENT_TAG|ezio22/argocd-node-app:${{ steps.dockertag.outputs.tag }}|" deployments/deployment.yml
             git config user.name 'GitHub Actions'
             git config user.email 'actions@github.com'
             git add deployments/deployment.yml
-            git commit -m "Update Docker image digest to ${{ steps.dockerhub.outputs.digest }}"
+            git commit -m "Update Docker image tag to ${{ steps.dockertag.outputs.tag }}"
             git push
           else
-            echo "No changes in image digest."
+            echo "No changes in image tag."
