Update argocd.yml

diff --git a/.github/workflows/argocd.yml b/.github/workflows/argocd.yml
--- a/.github/workflows/argocd.yml
+++ b/.github/workflows/argocd.yml
@@ -17,6 +17,7 @@ jobs:
           echo "Listing contents of the current directory:"
           pwd
           ls -alh
+
       - name: List files in deployments directory
         run: |
           echo "Listing contents of the deployments directory:"
@@ -26,22 +27,25 @@ jobs:
         id: dockerhub
         run: |
           DIGEST=$(curl -s "https://hub.docker.com/v2/repositories/ezio22/argocd-node-app/tags/latest" | jq -r '.images[] | select(.architecture=="amd64").digest')
+          if [[ -z "$DIGEST" || "$DIGEST" == "null" ]]; then
+            echo "Failed to fetch digest or digest is null."
+            exit 1
+          fi
           echo "Latest digest fetched: $DIGEST"
           echo "::set-output name=digest::$DIGEST"
       
       - name: Update the Deployment file if new image is available
         if: steps.dockerhub.outputs.digest != ''
         run: |
-          CURRENT_IMAGE=$(grep -o 'ezio22/argocd-node-app:[a-z0-9]*' deployments/deployment.yml)
-          echo "Current image in deployment.yml: $CURRENT_IMAGE"
-          if [ "$CURRENT_IMAGE" != "ezio22/argocd-node-app@${{ steps.dockerhub.outputs.digest }}" ]; then
+          CURRENT_DIGEST=$(grep -o 'ezio22/argocd-node-app@[a-z0-9]*' deployments/deployment.yml | cut -d '@' -f 2)
+          echo "Current digest in deployment.yml: $CURRENT_DIGEST"
+          if [ "$CURRENT_DIGEST" != "${{ steps.dockerhub.outputs.digest }}" ]; then
             echo "Updating deployment.yml with new digest..."
-            sed -i "s|${CURRENT_IMAGE}|ezio22/argocd-node-app@${{ steps.dockerhub.outputs.digest }}|" deployments/deployment.yml
+            sed -i "s|ezio22/argocd-node-app@${CURRENT_DIGEST}|ezio22/argocd-node-app@${{ steps.dockerhub.outputs.digest }}|" deployments/deployment.yml
             git config user.name 'GitHub Actions'
             git config user.email 'actions@github.com'
             git add deployments/deployment.yml
-            git commit -m "Update Docker image digest to ${{ steps.dockerhub.outputs.digest }}"
+            git diff-index --quiet HEAD || git commit -m "Update Docker image digest to ${{ steps.dockerhub.outputs.digest }}"
             git push
-           else
+          else
             echo "No changes in image digest."
-           fi
